# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['src\\tatva\\gui.py'],
    pathex=['src'],
    binaries=[],
    datas=[('website', 'website'), ('assets', 'assets'), ('BASELINE.md', '.'), ('OPTIMIZATION.md', '.')],
    hiddenimports=[
        'tatva',
        'tatva.compiler',
        'tatva.optimizer',
        'tatva.runner',
        'tatva.diagnostics',
        'tatva.config',
        'gui',
        'gui.tabs',
        'gui.tabs.scaffolding_tab',
        'scaffolding',
        'scaffolding.agent',
        'scaffolding.config',
        'scaffolding.logger',
        'scaffolding.executor',
        'scaffolding.llm_provider',
        'scaffolding.loop_agent',
        'webview',
        'onnx',
        'numpy',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='Tatva',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=['assets\\logo.png'],
)
